# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := lua_test

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

lua_test: 
	@echo "==== Building lua_test ($(config)) ===="
	@${MAKE} --no-print-directory -C obj -f Makefile

clean:
	@${MAKE} --no-print-directory -C obj -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lua_test"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
